<?php

namespace App\Console\Commands;

use App\Models\Army\TreeUnitTemplate;
use Illuminate\Console\Command;
use Illuminate\Support\Facades\File;

class RegisterTreeUnitTemplates extends Command
{
    protected $signature = 'register:tree_unit_templates';

    public function handle(): int
    {
        $templates = [
            'Station militaire de surveillance spatiale' => 'ArmeeAir/CentreSpatial/StationSurveillanceSpatiale.json',
            'Unité mobile de surveillance spatiale' => 'ArmeeAir/CentreSpatial/UniteMobileSurveillanceSpatiale.json',
            'Radar aérien' => 'ArmeeAir/DefenseControleAerien/RadarAerien.json',
            'Sémaphore' => 'ArmeeAir/DefenseControleAerien/Semaphore.json',
            'Escadron de sûreté aérienne' => 'ArmeeAir/DefenseControleAerien/SureteAerienne.json',
            'Escadron d\'excellence en manoeuvres aériennes' => 'ArmeeAir/ForcesAeriennesCombat/ExcellenceManoeuvresAeriennes.json',
            'Escadron d\'hélicoptères de combat' => 'ArmeeAir/ForcesAeriennesCombat/HelicopteresCombat.json',
            'Escadron de soutien aérien' => 'ArmeeAir/ForcesAeriennesCombat/SoutienAerien.json',
            'Fusiliers de l\'air' => 'ArmeeAir/ForcesProtectionAppui/FusiliersAir.json',
            'Pompiers de l\'air' => 'ArmeeAir/ForcesProtectionAppui/PompiersAir.json',
            'Escadron d\'hélicoptères' => 'ArmeeAir/MobiliteAerienne/Helicopteres.json',
            'Escadron de ravitaillement aérien' => 'ArmeeAir/MobiliteAerienne/RavitaillementAerien.json',
            'Escadron de transport aérien' => 'ArmeeAir/MobiliteAerienne/TransportAerien.json',
            'Escadron de transport aérien des commandements' => 'ArmeeAir/MobiliteAerienne/TransportAerienCommandements.json',
            'Escadron de transport aérien gouvernemental' => 'ArmeeAir/MobiliteAerienne/TransportAerienGouvernemental.json',
            'Régiment d\'artillerie' => 'ArmeeTerre/ForcesAppui/Artillerie.json',
            'Régiment d\'artillerie de montagne' => 'ArmeeTerre/ForcesAppui/ArtillerieMontagne.json',
            'Régiment d\'aviation légère' => 'ArmeeTerre/ForcesAppui/AviationLegere.json',
            'Régiment cynophile' => 'ArmeeTerre/ForcesAppui/Cynophile.json',
            'Régiment du génie' => 'ArmeeTerre/ForcesAppui/Genie.json',
            'Régiment du génie de montagne' => 'ArmeeTerre/ForcesAppui/GenieMontagne.json',
            'Régiment de cavalerie blindée' => 'ArmeeTerre/ForcesMelee/CavalerieBlindee.json',
            'Régiment de chars' => 'ArmeeTerre/ForcesMelee/Chars.json',
            'Régiment de chasseurs' => 'ArmeeTerre/ForcesMelee/Chasseurs.json',
            'Régiment de chasseurs alpins' => 'ArmeeTerre/ForcesMelee/ChasseursAlpins.json',
            'Régiment d\'infanterie' => 'ArmeeTerre/ForcesMelee/Infanterie.json',
            'Régiment de marines' => 'ArmeeTerre/ForcesMelee/Marines.json',
            'Régiment de projection rapide' => 'ArmeeTerre/ForcesMelee/ProjectionRapide.json',
            'Régiment de distribution des essences' => 'ArmeeTerre/ForcesSoutien/DistributionEssences.json',
            'Régiment de logistique' => 'ArmeeTerre/ForcesSoutien/Logistique.json',
            'Régiment de soutien à l\'homme' => 'ArmeeTerre/ForcesSoutien/SoutienHomme.json',
            'Régiment du train parachutiste' => 'ArmeeTerre/ForcesSoutien/TrainParachutiste.json',
            'Régiment de transmissions' => 'ArmeeTerre/ForcesSoutien/Transmissions.json',
            'Atelier de maintenance et de pliage de parachutes' => 'CGA/MaintenanceParachutes/AtelierMaintenancePliage.json',
            'Centre de stockage militaire' => 'CGA/SSMD/CentreStockage.json',
            'Station ferroviaire de la défense' => 'CGA/ServiceFerroviaire/StationFerroviaireDefense.json',
            'Datacenter de la défense' => 'CMSD/DGSIC/Datacenter.json',
            'Bataillon Darnia' => 'CMSD/ForcesSpeciales/Darnia.json',
            'Bataillon Génie de l\'air' => 'CMSD/ForcesSpeciales/GenieAir.json',
            'Bataillon RLD' => 'CMSD/ForcesSpeciales/RenseignementLongueDuree.json',
            'Groupement d\'artillerie parachutiste' => 'CMSD/GroupPara/GroupArtillPara.json',
            'Groupement de chasseurs parachutistes' => 'CMSD/GroupPara/GroupChassPara.json',
            'Groupement commando montagne' => 'CMSD/GroupPara/GroupComdoMont.json',
            'Groupement génie parachutiste' => 'CMSD/GroupPara/GroupGeniePara.json',
            'Groupement d\'infanterie parachutiste' => 'CMSD/GroupPara/GroupInfanteriePara.json',
            'Groupement spécial des Marines' => 'CMSD/GroupPara/GroupSpecialMarines.json',
            'Groupe de protection de l\'hôpital militaire' => 'CMSD/ProtectionHopitaux/GroupeProtection.json',
            'Antenne fédérale de la sécurité intérieure' => 'CMSD/SecuriteInterieure/Antenne.json',
            'Champ de lancement de missiles nucléaires' => 'CMSD/ServiceSpecialNucleaire/ChampLancementMissilesNucleaires.json',
            'Escadron de dépôts spéciaux' => 'CMSD/ServiceSpecialNucleaire/EscadronDepotSpecial.json',
            'Black site' => 'CMSD/ServicesSecrets/RechercheRenseignementEtranger/RenseignementHumain/BlackSite.json',
            'Station d\'ambassade' => 'CMSD/ServicesSecrets/RechercheRenseignementEtranger/StationsAmbassade/Station.json',
            'Station conjointe de renseignement' => 'CMSD/ServicesSecrets/RechercheRenseignementEtranger/StationsConjointesRenseignement/Station.json',
            'Sous-direction fédérale des actions défensives électroniques' => 'CMSD/ServicesSecrets/Technique/GuerreElectronique/SousdirDefense.json',
            'Frégate de renseignement' => 'CMSD/ServicesSecrets/Technique/RenseignementTechnique/FregateRenseignement.json',
            'Groupe mobile de renseignement électronique' => 'CMSD/ServicesSecrets/Technique/RenseignementTechnique/GroupeMobileRensElectro.json',
            'Groupe de gestion des infrastructures aériennes' => 'EMIA/GestionBases/InfrasAeriennes.json',
            'Groupe de gestion des infrastructures navales' => 'EMIA/GestionBases/InfrasNavales.json',
            'Groupe de gestion des infrastructures radars' => 'EMIA/GestionBases/InfrasRadars.json',
            'Groupe de gestion des infrastructures terrestres' => 'EMIA/GestionBases/InfrasTerrestres.json',
            'Centre de triage de la poste militaire' => 'EMIA/PosteInterArmees/CentreTriage.json',
            'Ecole de l\'appui aérien' => 'Ecole/Ecoles/FormationAeronautique/AppuiAerien.json',
            'Ecole d\'aviation de chasse' => 'Ecole/Ecoles/FormationAeronautique/AviationChasse.json',
            'Ecole d\'aviation militaire' => 'Ecole/Ecoles/FormationAeronautique/AviationMilitaire.json',
            'Centre inter-armées de formation à l\'appui-feu' => 'Ecole/Ecoles/FormationAeronautique/FormationAppuiFeu.json',
            'Centre d\'instruction des équipages' => 'Ecole/Ecoles/FormationAeronautique/InstructionEquipages.json',
            'Centre d\'instruction au parachutisme' => 'Ecole/Ecoles/FormationAeronautique/InstructionParachutisme.json',
            'Ecole des métiers d\'essais en vol' => 'Ecole/Ecoles/FormationAeronautique/MetiersEssaisVol.json',
            'Ecole de pilotage d\'hélicoptères' => 'Ecole/Ecoles/FormationAeronautique/PilotageHelicoptere.json',
            'Ecole d\'artillerie' => 'Ecole/Ecoles/FormationCombatTerrestre/Artillerie.json',
            'Ecole de cavalerie' => 'Ecole/Ecoles/FormationCombatTerrestre/Cavalerie.json',
            'Ecole de combat en montagne' => 'Ecole/Ecoles/FormationCombatTerrestre/CombatMontagne.json',
            'Ecole de combat urbain' => 'Ecole/Ecoles/FormationCombatTerrestre/CombatUrbain.json',
            'Ecole de formation initiale' => 'Ecole/Ecoles/FormationCombatTerrestre/FormationInitiale.json',
            'Ecole du génie' => 'Ecole/Ecoles/FormationCombatTerrestre/Genie.json',
            'Ecole d\'infanterie' => 'Ecole/Ecoles/FormationCombatTerrestre/Infanterie.json',
            'Centre d\'instruction au ski militaire' => 'Ecole/Ecoles/FormationCombatTerrestre/InstructionSkiMilitaire.json',
            'Ecole d\'officiers' => 'Ecole/Ecoles/FormationCommandementRenseignement/FormationOfficiers.json',
            'Ecole de sous-officiers' => 'Ecole/Ecoles/FormationCommandementRenseignement/FormationSousofficiers.json',
            'Ecole d\'image et de journalisme' => 'Ecole/Ecoles/FormationCommandementRenseignement/ImageJournalisme.json',
            'Ecole d\'enseignement du commandement' => 'Ecole/Ecoles/FormationCommandementRenseignement/InterpretationImagerie.json',
            'Ecole navale' => 'Ecole/Ecoles/FormationNavale/FormationNavale.json',
            'Ecole navale de garde-côtière' => 'Ecole/Ecoles/FormationNavale/GardeCotiere.json',
            'Ecole navale de sous-mariniers' => 'Ecole/Ecoles/FormationNavale/SousMariniers.json',
            'Ecole de la garde nationale' => 'Ecole/Ecoles/FormationSecuriteInterieure/GardeNationale.json',
            'Ecole des forces de sécurité drarekstanes' => 'Ecole/Ecoles/FormationSecuriteInterieure/Police.json',
            'Ecole policière de motocyclisme' => 'Ecole/Ecoles/FormationSecuriteInterieure/PoliceMoto.json',
            'Centre d\'instruction cynophile' => 'Ecole/Ecoles/FormationSoutienLogistique/InstructionCynophile.json',
            'Ecole de santé des armées' => 'Ecole/Ecoles/FormationSoutienLogistique/Sante.json',
            'Centre d\'instruction au secourisme en milieu hostile' => 'Ecole/Ecoles/FormationSoutienLogistique/SecourismeMilieuHostile.json',
            'Lycée militaire' => 'Ecole/EtablissementsScolaires/LyceeMilitaire.json',
            'Centre d\'entraînement et d\'aguerrissement militaire' => 'Entrainement/CEAM.json',
            'Centre d\'entraînement' => 'Entrainement/CentreEntrainement.json',
            'Centre d\'entrainement au combat urbain' => 'Entrainement/CentreEntrainementCombatUrbain.json',
            'Site d\'essais AMM' => 'CCPM/SiteEssaisAMM.json',
            'Site d\'essais UMM' => 'CCPM/SiteEssaisUMM.json',
            'Antenne d\'escortes de détenus' => 'FSD/AdministrationPenitentiaire/AntenneEscorteDetenu.json',
            'Centre de rétention administrative' => 'FSD/AdministrationPenitentiaire/CentreRetentionAdmin.json',
            'Prison de basse sécurité' => 'FSD/AdministrationPenitentiaire/PrisonBasseSecurite.json',
            'Prison de haute sécurité' => 'FSD/AdministrationPenitentiaire/PrisonHauteSecurite.json',
            'Prison militaire' => 'FSD/AdministrationPenitentiaire/PrisonMilitaire.json',
            'Prison pour mineurs' => 'FSD/AdministrationPenitentiaire/PrisonMineur.json',
            'Prison de moyenne sécurité' => 'FSD/AdministrationPenitentiaire/PrisonMoyenneSecurite.json',
            'Antenne fédérale du BNS' => 'FSD/BureauNationalSecurite/Antenne.json',
            'Poste de douanes' => 'FSD/Douanes/Douanes.json',
            'Douanes aéroportuaires' => 'FSD/Douanes/DouanesAeroportuaires.json',
            'Douanes maritimes' => 'FSD/Douanes/DouanesMaritimes.json',
            'Police militaire' => 'FSD/PoliceMilitaire/Unite.json',
            'Direction fédérale anti-criminalité' => 'FSD/PoliceNationale/AntiCriminalite/DirectionFederale.json',
            'Groupe anti-criminalité' => 'FSD/PoliceNationale/AntiCriminalite/Groupe.json',
            'Direction fédérale anti-stupéfiants' => 'FSD/PoliceNationale/AntiStupefiants/DirectionFederale.json',
            'Groupe anti-stupéfiants' => 'FSD/PoliceNationale/AntiStupefiants/Groupe.json',
            'Direction fédérale des appels de secours' => 'FSD/PoliceNationale/CentreReceptionAppelSecours/DirectionFederale.json',
            'Centre de réception des appels de secours' => 'FSD/PoliceNationale/CentreReceptionAppelSecours/CentreReceptionAppelSecours.json',
            'Direction fédérale de la vidéo-surveillance' => 'FSD/PoliceNationale/CentreVideoSurveillance/DirectionFederale.json',
            'Centre de vidéo-surveillance' => 'FSD/PoliceNationale/CentreVideoSurveillance/CentreVideoSurveillance.json',
            'Pôle fédéral de la criminalité financière' => 'FSD/PoliceNationale/CriminaliteFinanciere.json',
            'Direction fédérale de la police cynophile' => 'FSD/PoliceNationale/Cynophile/DirectionFederale.json',
            'Groupe cynophile' => 'FSD/PoliceNationale/Cynophile/Groupe.json',
            'Direction fédérale du déminage' => 'FSD/PoliceNationale/Deminage/DirectionFederale.json',
            'Groupement de déminage' => 'FSD/PoliceNationale/Deminage/Groupement.json',
            'Pôle fédéral pour les disparitions' => 'FSD/PoliceNationale/Disparitions.json',
            'Pôle fédéral contre la cybercriminalité' => 'FSD/PoliceNationale/GroupeLutteCyber.json',
            'Direction fédérale des interventions risquées' => 'FSD/PoliceNationale/GroupesIntervention/DirectionFederale.json',
            'Groupe d\'intervention des forces de sécurité' => 'FSD/PoliceNationale/GroupesIntervention/GroupeIntervention.json',
            'Direction fédérale du maintien de l\'ordre' => 'FSD/PoliceNationale/MaintienOrdre/DirectionFederale.json',
            'Groupe anti-émeutes' => 'FSD/PoliceNationale/MaintienOrdre/GroupeAntiEmeute.json',
            'Direction fédérale de la police de l\'air' => 'FSD/PoliceNationale/PoliceAir/DirectionFederale.json',
            'Police de l\'air' => 'FSD/PoliceNationale/PoliceAir/PoliceAir.json',
            'Police alpine' => 'FSD/PoliceNationale/PoliceAlpine.json',
            'Police fluviale' => 'FSD/PoliceNationale/PoliceFluviale.json',
            'Direction fédérale de la police judiciaire' => 'FSD/PoliceNationale/PoliceJudiciaire/DirectionFederale.json',
            'Groupement de police judiciaire' => 'FSD/PoliceNationale/PoliceJudiciaire/Groupement.json',
            'Police maritime' => 'FSD/PoliceNationale/PoliceMaritime.json',
            'Direction fédérale motocycliste' => 'FSD/PoliceNationale/PoliceMotocycliste/DirectionFederale.json',
            'Caserne motocycliste' => 'FSD/PoliceNationale/PoliceMotocycliste/Caserne.json',
            'Direction fédérale de la police de proximité' => 'FSD/PoliceNationale/PoliceProximite/DirectionFederale.json',
            'Groupement de police de proximité' => 'FSD/PoliceNationale/PoliceProximite/Groupement.json',
            'Direction fédérale de la police scientifique' => 'FSD/PoliceNationale/PoliceScientifique/DirectionFederale.json',
            'Groupement de police scientifique' => 'FSD/PoliceNationale/PoliceScientifique/Groupement.json',
            'Direction fédérale police-secours' => 'FSD/PoliceNationale/PoliceSecours/DirectionFederale.json',
            'Groupe police-secours' => 'FSD/PoliceNationale/PoliceSecours/Groupe.json',
            'Police universitaire' => 'FSD/PoliceNationale/PoliceUniversitaire.json',
            'Direction fédérale de la protection de la famille et de l\'enfance' => 'FSD/PoliceNationale/ProtectionFamilleEnfance/DirectionFederale.json',
            'Groupe de protection de la famille et de l\'enfance' => 'FSD/PoliceNationale/ProtectionFamilleEnfance/Groupe.json',
            'Direction fédérale de la protection des personnes' => 'FSD/PoliceNationale/ProtectionPersonnes/DirectionFederale.json',
            'Groupement de protection des personnes' => 'FSD/PoliceNationale/ProtectionPersonnes/ProtectionPersonnes.json',
            'Direction fédérale de la sécurisation des transports' => 'FSD/PoliceNationale/SecurisationTransports/DirectionFederale.json',
            'Groupe de sécurisation des transports' => 'FSD/PoliceNationale/SecurisationTransports/SecurisationTransports.json',
            'Direction fédérale de la sécurité routière' => 'FSD/PoliceNationale/SecuriteRoutiere/DirectionFederale.json',
            'Groupement de sécurité routière' => 'FSD/PoliceNationale/SecuriteRoutiere/Groupement.json',
            'Escadron de la garde nationale' => 'GardeNationale/Escadron.json',
            'Régiment de la garde nationale' => 'GardeNationale/Regiment.json',
            'Flotte de combat maritime' => 'MarineNationale/ForceActionNavale/CombatMaritime.json',
            'Frégate furtive' => 'MarineNationale/ForceActionNavale/FregateFurtive.json',
            'Flottille de reconnaissance embarquée' => 'MarineNationale/ForceNavaleStrategique/FlottilleReconnaissanceEmbarquee.json',
            'Flottille de chasse embarquée' => 'MarineNationale/ForceNavaleStrategique/FlottilleChasseEmbarquee.json',
            'Groupe aéronaval' => 'MarineNationale/ForceNavaleStrategique/MoyensAeronavales.json',
            'Groupe amphibie' => 'MarineNationale/ForceNavaleStrategique/MoyensAmphibies.json',
            'Bâtiment d\'essais et de mesures' => 'MarineNationale/ForceSoutienNaval/BatimentEssaisMesures.json',
            'Bâtiment océano-hydrographique' => 'MarineNationale/ForceSoutienNaval/BatimentOceanoHydro.json',
            'Navire-hôpital' => 'MarineNationale/ForceSoutienNaval/NavireHopital.json',
            'Ravitailleur maritime' => 'MarineNationale/ForceSoutienNaval/RavitailleurMaritime.json',
            'Groupement fédéral de soutien à la flotte' => 'MarineNationale/ForceSoutienNaval/SoutienFlotte.json',
            'Transporteur autonome léger' => 'MarineNationale/ForceSoutienNaval/TransporteurAutonomeLeger.json',
            'Bâtiment ravitailleur de sous-marin' => 'MarineNationale/ForceStrategiqueSousMarine/BatimentRavitailleurSousmarin.json',
            'Sous-marin nucléaire d\'attaque' => 'MarineNationale/ForceStrategiqueSousMarine/SousmarinNucleaireAttaque.json',
            'Sous-marin nucléaire lanceur d\'engins' => 'MarineNationale/ForceStrategiqueSousMarine/SousmarinNucleaireLanceurEngins.json',
            'Fusiliers marins' => 'MarineNationale/SecuriteNavale/FusilMarin.json',
            'Base de la garde-côtière' => 'MarineNationale/SecuriteNavale/GardeCotiere.json',
            'Marins-pompier' => 'MarineNationale/SecuriteNavale/MarinPompier.json',
            'Groupement fédéral de plongeurs-démineurs' => 'MarineNationale/SecuriteNavale/PlongeurDemineur.json',
            'Flotte de protection côtière' => 'MarineNationale/SecuriteNavale/ProtectionCotiere.json',
            'Hôpital militaire' => 'Medical/HopitalMilitaire.json',
            'Régiment médical' => 'Medical/RegimentMedical.json',
            'Poste de santé régimentaire' => 'Medical/SanteRegiment/SanteRegiment.json',
            'Centre de récupération physique et physiologique' => 'Projection/CentreRecupPP.json',
            'Groupe de gestion fédéral des infrastructures policières' => 'EMIA/GestionBases/InfrasPolicieres.json',
            'Centre d\'expertise en combat urbain' => 'CCPM/CentreExpertiseCombatUrbain.json',
            'Centre de l\'expérimentation des stratégies' => 'CCPM/CentreExperimentationStrategies.json',
            'Laboratoire des matériaux furtifs' => 'CCPM/NBIC/LaboratoireMateriauxFurtifs.json',
            'Laboratoire des nanostructures pour l\'armement' => 'CCPM/NBIC/LaboratoireNanostructuresArmement.json',
            'Laboratoire de l\'ingénierie biologique' => 'CCPM/NBIC/LaboratoireIngenierieBiologique.json',
            'Laboratoire des interfaces homme-machine' => 'CCPM/NBIC/LaboratoireInterfacesHommeMachine.json',
            'Centre inter-armées d\'intelligence artificielle' => 'CCPM/NBIC/CentreInterArmeesIntelligenceArtificielle.json',
            'Laboratoire de la détonique et des ondes de choc' => 'CCPM/EtudesExplosifs/LaboratoireDetoniqueOndesChoc.json',
            'Laboratoire de la formulation des nouveaux explosifs' => 'CCPM/EtudesExplosifs/LaboratoireFormulationExplosifs.json',
        ];

        foreach ($templates as $template_name => $file_path) {
            $structure = json_decode(File::get(storage_path().'/igp/generation/'.$file_path), true);

            $this->registerTemplate($template_name, $structure);
        }

        return Command::SUCCESS;
    }

    private function registerTemplate(string $template_name, array $structure): void
    {
        $template = TreeUnitTemplate::query()->where('name', $template_name)->firstOr(function () use ($template_name) {
            $template = new TreeUnitTemplate();
            $template->name = $template_name;

            return $template;
        });

        $template->items = $structure;
        $template->save();
    }
}